export type ApiSurface =
  | "admin"
  | "auth"
  | "public"
  | "pro"
  | "reports"
  | "v1"
  | "webhook";

export type ApiAuthRequirement =
  | "public"
  | "session"
  | "admin"
  | "admin_or_analyst"
  | "premium"
  | "api_key"
  | "api_key_or_public_read"
  | "cron_or_admin"
  | "secret"
  | "stripe_signature";

export type ApiCostPolicy =
  | "none"
  | "provider_ai"
  | "agent_execution"
  | "report_generation"
  | "pdf_generation"
  | "webhook";

export type ApiFailBehavior = "fail_closed" | "fail_open_audit_only";

export interface ApiRoutePolicy {
  routeId: string;
  routeTemplate: string;
  file: string;
  surface: ApiSurface;
  allowedMethods: readonly string[];
  authRequirement: ApiAuthRequirement;
  rateLimitBucket: string;
  costPolicy: ApiCostPolicy;
  telemetryEvent: string;
  failBehavior: ApiFailBehavior;
  auditPriority: "critical" | "high" | "medium" | "low";
  notes?: string;
}

export const ROUTE_POLICY_VERSION = "2026-08-15.api-hardening.v1";

export const API_ROUTE_POLICIES = [
  {
    routeId: "api.admin.agents.runs.execute",
    routeTemplate: "/api/admin/agents/runs/[id]/execute",
    file: "src/app/api/admin/agents/runs/[id]/execute/route.ts",
    surface: "admin",
    allowedMethods: ["POST"],
    authRequirement: "admin",
    rateLimitBucket: "admin-agent-execute",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.agents.runs.execute",
    failBehavior: "fail_closed",
    auditPriority: "critical",
  },
  {
    routeId: "api.admin.agents.tick",
    routeTemplate: "/api/admin/agents/tick",
    file: "src/app/api/admin/agents/tick/route.ts",
    surface: "admin",
    allowedMethods: ["GET", "POST"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.agents.tick",
    failBehavior: "fail_closed",
    auditPriority: "critical",
  },
  {
    routeId: "api.admin.crew",
    routeTemplate: "/api/admin/crew",
    file: "src/app/api/admin/crew/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.crew",
    failBehavior: "fail_closed",
    auditPriority: "low",
    notes: "Crew roster and plain-English activity log; read-only, no provider calls.",
  },
  {
    routeId: "api.admin.stripe.pro_prices",
    routeTemplate: "/api/admin/stripe/pro-prices",
    file: "src/app/api/admin/stripe/pro-prices/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.stripe.pro_prices",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes:
      "Sets up the six Pro tier prices in Stripe if missing (idempotent by lookup key) and opens then expires one checkout per price to prove it works; no charge.",
  },
  {
    routeId: "api.admin.stripe.portal_check",
    routeTemplate: "/api/admin/stripe/portal-check",
    file: "src/app/api/admin/stripe/portal-check/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.stripe.portal_check",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes:
      "Reads the default Stripe customer portal configuration and opens one portal session for an existing customer to prove Manage billing works; no charge, nothing changed.",
  },
  {
    routeId: "api.admin.email_check",
    routeTemplate: "/api/admin/email-check",
    file: "src/app/api/admin/email-check/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.email_check",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes:
      "Shows the outgoing email setup (From address, key last 4, Resend domain verification); with ?send=1 emails the admin their own confirmation link and returns Resend's answer.",
  },
  {
    routeId: "api.admin.stripe.webhook_check",
    routeTemplate: "/api/admin/stripe/webhook-check",
    file: "src/app/api/admin/stripe/webhook-check/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.stripe.webhook_check",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes:
      "Lists the Stripe webhook endpoints that point at this site and the handled events each one does not send; read-only, nothing changed.",
  },
  {
    routeId: "api.admin.flow",
    routeTemplate: "/api/admin/flow",
    file: "src/app/api/admin/flow/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.flow",
    failBehavior: "fail_closed",
    auditPriority: "low",
    notes: "Live flow page: latest institution moves per agent and cached queue sizes; read-only, no provider calls.",
  },
  {
    routeId: "api.admin.documents",
    routeTemplate: "/api/admin/documents/[id]",
    file: "src/app/api/admin/documents/[id]/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.documents",
    failBehavior: "fail_closed",
    auditPriority: "low",
    notes: "Redirects to a 1-hour presigned R2 link for a stored source document (the document vault).",
  },
  {
    routeId: "api.admin.crew.daily_brief",
    routeTemplate: "/api/admin/crew/daily-brief",
    file: "src/app/api/admin/crew/daily-brief/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.daily_brief",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Daily Atlas brief email; one visible run per day, no provider calls.",
  },
  {
    routeId: "api.admin.crew.fee_alerts",
    routeTemplate: "/api/admin/crew/fee-alerts",
    file: "src/app/api/admin/crew/fee-alerts/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.fee_alerts",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Daily Atlas fee-change alerts to readers' saved institutions; one visible run per day, no provider calls.",
  },
  {
    routeId: "api.admin.crew.briefing_refresh",
    routeTemplate: "/api/admin/crew/briefing-refresh",
    file: "src/app/api/admin/crew/briefing-refresh/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.briefing_refresh",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Daily Hamilton check that every institution workspace has this quarter's stored briefing; deterministic, no provider calls.",
  },
  {
    routeId: "api.admin.crew.competitor_alerts",
    routeTemplate: "/api/admin/crew/competitor-alerts",
    file: "src/app/api/admin/crew/competitor-alerts/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.competitor_alerts",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Daily Hamilton in-app alerts to institution workspaces when a local competitor's verified fee changes; no email, no provider calls.",
  },
  {
    routeId: "api.admin.crew.pro_digest",
    routeTemplate: "/api/admin/crew/pro-digest",
    file: "src/app/api/admin/crew/pro-digest/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.pro_digest",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Monday Atlas digest for Pro readers; one visible run per week, no provider calls; sends only while PRO_EMAILS_ENABLED is on.",
  },
  {
    routeId: "api.admin.reports.schedule",
    routeTemplate: "/api/admin/reports/schedule",
    file: "src/app/api/admin/reports/schedule/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "report_generation",
    telemetryEvent: "api.admin.reports.schedule",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Queues the scheduled public reports (National Fee Index quarterly, Monthly Pulse monthly) as visible Hamilton runs.",
  },
  {
    routeId: "api.admin.crew.lead_watch",
    routeTemplate: "/api/admin/crew/lead-watch",
    file: "src/app/api/admin/crew/lead-watch/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.lead_watch",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Hourly Atlas lead watch: emails James about report requests unanswered for 24h and leads whose emails failed; no provider calls.",
  },
  {
    routeId: "api.admin.crew.indexnow",
    routeTemplate: "/api/admin/crew/indexnow",
    file: "src/app/api/admin/crew/indexnow/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.indexnow",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Daily Atlas IndexNow ping: tells Bing which institution pages got new published fees in the last 25h; free, no provider calls.",
  },
  {
    routeId: "api.admin.crew.marketing",
    routeTemplate: "/api/admin/crew/marketing",
    file: "src/app/api/admin/crew/marketing/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.marketing",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Monthly Hamilton marketing run: scores sent campaigns, then writes this month's drafts (one budgeted provider step). Never sends.",
  },
  {
    routeId: "api.admin.crew.content",
    routeTemplate: "/api/admin/crew/content",
    file: "src/app/api/admin/crew/content/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.content",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Weekly content run: drafts posts into the content queue for James to approve; no provider calls, never posts.",
  },
  {
    routeId: "api.admin.crew.contacts",
    routeTemplate: "/api/admin/crew/contacts",
    file: "src/app/api/admin/crew/contacts/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.contacts",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "NIELSEN's contact finder: reads prospect websites (robots.txt honored) for published executive addresses; no provider calls, nothing sends. Not in vercel.json until James says go.",
  },
  {
    routeId: "api.admin.growth.contacts",
    routeTemplate: "/api/admin/growth/contacts",
    file: "src/app/api/admin/growth/contacts/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.growth.contacts",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes: "CSV download of the prospect contacts NIELSEN found; admins only, read-only.",
  },
  {
    routeId: "api.admin.crew.growth_score",
    routeTemplate: "/api/admin/crew/growth-score",
    file: "src/app/api/admin/crew/growth-score/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.growth_score",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Weekly growth scoring: scores posted queue items from tracked visits and leads; no provider calls. Not in vercel.json until James says go.",
  },
  {
    routeId: "api.admin.growth.intake",
    routeTemplate: "/api/admin/growth/intake",
    file: "src/app/api/admin/growth/intake/route.ts",
    surface: "admin",
    allowedMethods: ["GET", "POST"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.growth.intake",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Scheduled Claude Code sessions file drafts and PR links into the growth queue (one growth run each); GET returns an agent's lessons from skip reasons. No personal data, never posts or sends.",
  },
  {
    routeId: "api.admin.content.card",
    routeTemplate: "/api/admin/content/card/[id]",
    file: "src/app/api/admin/content/card/[id]/route.tsx",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.content.card",
    failBehavior: "fail_closed",
    auditPriority: "low",
    notes: "Renders a content-queue draft's square card (PNG) from its stored facts, for James to download and post.",
  },
  {
    routeId: "api.admin.marketing.approve",
    routeTemplate: "/api/admin/marketing/approve",
    file: "src/app/api/admin/marketing/approve/route.ts",
    surface: "admin",
    allowedMethods: ["POST"],
    authRequirement: "admin",
    rateLimitBucket: "admin-agent-execute",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.marketing.approve",
    failBehavior: "fail_closed",
    auditPriority: "critical",
    notes: "James approves a month's marketing drafts; the only path that sends marketing email.",
  },
  {
    routeId: "api.admin.crew.scoreboard",
    routeTemplate: "/api/admin/crew/scoreboard",
    file: "src/app/api/admin/crew/scoreboard/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.scoreboard",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Daily Atlas answer-key score and scoreboard snapshot; one visible run per day, no provider calls.",
  },
  {
    routeId: "api.admin.crew.studies",
    routeTemplate: "/api/admin/crew/studies",
    file: "src/app/api/admin/crew/studies/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.studies",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Hamilton's daily studies run; stores a study only when its data period is new. Deterministic, no provider calls.",
  },
  {
    routeId: "api.admin.registry.tick",
    routeTemplate: "/api/admin/registry/tick",
    file: "src/app/api/admin/registry/tick/route.ts",
    surface: "admin",
    allowedMethods: ["GET", "POST"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.registry.tick",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Regulatory-registry cron: schedules and runs one deterministic partition step; no provider calls.",
  },
  {
    routeId: "api.admin.registry.run",
    routeTemplate: "/api/admin/registry/run",
    file: "src/app/api/admin/registry/run/route.ts",
    surface: "admin",
    allowedMethods: ["POST"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.registry.run",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Queues one regulatory-registry partition as a visible Magellan run; deterministic, no provider calls.",
  },
  {
    routeId: "api.admin.job_health",
    routeTemplate: "/api/admin/job-health",
    file: "src/app/api/admin/job-health/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.job_health",
    failBehavior: "fail_open_audit_only",
    auditPriority: "medium",
    notes: "Public health summary; keep deterministic and read-only.",
  },
  {
    routeId: "api.alerts",
    routeTemplate: "/api/alerts",
    file: "src/app/api/alerts/route.ts",
    surface: "public",
    allowedMethods: ["GET", "POST", "DELETE"],
    authRequirement: "session",
    rateLimitBucket: "account-alerts",
    costPolicy: "none",
    telemetryEvent: "api.alerts",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.alerts.unsubscribe",
    routeTemplate: "/api/alerts/unsubscribe",
    file: "src/app/api/alerts/unsubscribe/route.ts",
    surface: "public",
    allowedMethods: ["POST"],
    authRequirement: "secret",
    rateLimitBucket: "account-alerts",
    costPolicy: "none",
    telemetryEvent: "api.alerts.unsubscribe",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Signed one-click unsubscribe from fee-change alerts (RFC 8058) and the /email-preferences button.",
  },
  {
    routeId: "api.auth.logout",
    routeTemplate: "/api/auth/logout",
    file: "src/app/api/auth/logout/route.ts",
    surface: "auth",
    allowedMethods: ["POST"],
    authRequirement: "session",
    rateLimitBucket: "auth",
    costPolicy: "none",
    telemetryEvent: "api.auth.logout",
    failBehavior: "fail_closed",
    auditPriority: "low",
  },
  {
    routeId: "api.guides.saved_institutions",
    routeTemplate: "/api/guides/saved-institutions",
    file: "src/app/api/guides/saved-institutions/route.ts",
    surface: "public",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "account-alerts",
    costPolicy: "none",
    telemetryEvent: "api.guides.saved_institutions",
    failBehavior: "fail_open_audit_only",
    auditPriority: "low",
    notes:
      "Personalisation island for static guide pages. Signed-out callers get an empty list, never a 401, so the page never depends on it.",
  },
  {
    routeId: "api.hamilton.chat",
    routeTemplate: "/api/hamilton/chat",
    file: "src/app/api/hamilton/chat/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "admin_or_analyst",
    rateLimitBucket: "provider-ai",
    costPolicy: "provider_ai",
    telemetryEvent: "api.hamilton.chat",
    failBehavior: "fail_closed",
    auditPriority: "critical",
  },
  {
    routeId: "api.hamilton.conversation.messages",
    routeTemplate: "/api/hamilton/conversations/[id]/messages",
    file: "src/app/api/hamilton/conversations/[id]/messages/route.ts",
    surface: "pro",
    allowedMethods: ["GET"],
    authRequirement: "admin_or_analyst",
    rateLimitBucket: "pro-read",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.conversation.messages",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.hamilton.conversations",
    routeTemplate: "/api/hamilton/conversations",
    file: "src/app/api/hamilton/conversations/route.ts",
    surface: "pro",
    allowedMethods: ["GET", "POST"],
    authRequirement: "admin_or_analyst",
    rateLimitBucket: "pro-write",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.conversations",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.hamilton.ask",
    routeTemplate: "/api/hamilton/ask",
    file: "src/app/api/hamilton/ask/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "pro-write",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.ask",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.hamilton.ask.market",
    routeTemplate: "/api/hamilton/ask/market",
    file: "src/app/api/hamilton/ask/market/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "pro-write",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.ask.market",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.hamilton.ask.memo",
    routeTemplate: "/api/hamilton/ask/memo",
    file: "src/app/api/hamilton/ask/memo/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "provider-ai",
    costPolicy: "provider_ai",
    telemetryEvent: "api.hamilton.ask.memo",
    failBehavior: "fail_closed",
    auditPriority: "critical",
  },
  {
    routeId: "api.hamilton.uploads",
    routeTemplate: "/api/hamilton/uploads",
    file: "src/app/api/hamilton/uploads/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "pro-write",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.uploads",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.hamilton.uploads.apply",
    routeTemplate: "/api/hamilton/uploads/apply",
    file: "src/app/api/hamilton/uploads/apply/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "pro-write",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.uploads.apply",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.hamilton.decisions",
    routeTemplate: "/api/hamilton/decisions",
    file: "src/app/api/hamilton/decisions/route.ts",
    surface: "pro",
    allowedMethods: ["GET"],
    authRequirement: "premium",
    rateLimitBucket: "pro-write",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.decisions",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.hamilton.decisions.detail",
    routeTemplate: "/api/hamilton/decisions/[id]",
    file: "src/app/api/hamilton/decisions/[id]/route.ts",
    surface: "pro",
    allowedMethods: ["GET", "POST"],
    authRequirement: "premium",
    rateLimitBucket: "pro-write",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.decisions.detail",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.hamilton.deliverables",
    routeTemplate: "/api/hamilton/deliverables",
    file: "src/app/api/hamilton/deliverables/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "pro-write",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.deliverables",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.hamilton.simulate",
    routeTemplate: "/api/hamilton/simulate",
    file: "src/app/api/hamilton/simulate/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "provider-ai",
    costPolicy: "provider_ai",
    telemetryEvent: "api.hamilton.simulate",
    failBehavior: "fail_closed",
    auditPriority: "critical",
  },
  {
    routeId: "api.health",
    routeTemplate: "/api/health",
    file: "src/app/api/health/route.ts",
    surface: "public",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "health",
    costPolicy: "none",
    telemetryEvent: "api.health",
    failBehavior: "fail_open_audit_only",
    auditPriority: "low",
  },
  {
    routeId: "api.institutions.evidence",
    routeTemplate: "/api/institutions/[id]/evidence",
    file: "src/app/api/institutions/[id]/evidence/route.ts",
    surface: "public",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.institutions.evidence",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.institutions",
    routeTemplate: "/api/institutions",
    file: "src/app/api/institutions/route.ts",
    surface: "public",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.institutions",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.leads",
    routeTemplate: "/api/leads",
    file: "src/app/api/leads/route.ts",
    surface: "public",
    allowedMethods: ["POST"],
    authRequirement: "public",
    rateLimitBucket: "lead-write",
    costPolicy: "none",
    telemetryEvent: "api.leads",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.leads.subscription",
    routeTemplate: "/api/leads/subscription",
    file: "src/app/api/leads/subscription/route.ts",
    surface: "public",
    allowedMethods: ["POST"],
    authRequirement: "public",
    rateLimitBucket: "lead-subscription",
    costPolicy: "none",
    telemetryEvent: "api.leads.subscription",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Confirm and one-click unsubscribe links; its own bucket so an unsubscribe is never rate limited.",
  },
  {
    routeId: "api.leads.reader",
    routeTemplate: "/api/leads/reader",
    file: "src/app/api/leads/reader/route.ts",
    surface: "public",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.leads.reader",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Returns the confirmed reader's own address from their signed httpOnly cookie, so free report forms skip the email field.",
  },
  {
    routeId: "api.track.touch",
    routeTemplate: "/api/track/touch",
    file: "src/app/api/track/touch/route.ts",
    surface: "public",
    allowedMethods: ["POST"],
    authRequirement: "public",
    rateLimitBucket: "touch-write",
    costPolicy: "none",
    telemetryEvent: "api.track.touch",
    failBehavior: "fail_closed",
    auditPriority: "low",
    notes: "One tracked-link visit per browser session (UTM values, landing path, referrer host); no personal data, no provider calls.",
  },
  {
    routeId: "api.pro.report_pdf",
    routeTemplate: "/api/pro/report-pdf",
    file: "src/app/api/pro/report-pdf/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "pro-export",
    costPolicy: "pdf_generation",
    telemetryEvent: "api.pro.report_pdf",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.reports.download",
    routeTemplate: "/api/reports/[id]/download",
    file: "src/app/api/reports/[id]/download/route.ts",
    surface: "reports",
    allowedMethods: ["GET"],
    authRequirement: "session",
    rateLimitBucket: "report-read",
    costPolicy: "none",
    telemetryEvent: "api.reports.download",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.reports.status",
    routeTemplate: "/api/reports/[id]/status",
    file: "src/app/api/reports/[id]/status/route.ts",
    surface: "reports",
    allowedMethods: ["GET", "PATCH"],
    authRequirement: "session",
    rateLimitBucket: "report-read",
    costPolicy: "none",
    telemetryEvent: "api.reports.status",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.reports.catalog",
    routeTemplate: "/api/reports/catalog",
    file: "src/app/api/reports/catalog/route.ts",
    surface: "reports",
    allowedMethods: ["GET"],
    authRequirement: "session",
    rateLimitBucket: "report-read",
    costPolicy: "none",
    telemetryEvent: "api.reports.catalog",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.reports.email_gate",
    routeTemplate: "/api/reports/email-gate",
    file: "src/app/api/reports/email-gate/route.ts",
    surface: "reports",
    allowedMethods: ["POST"],
    authRequirement: "public",
    rateLimitBucket: "lead-write",
    costPolicy: "none",
    telemetryEvent: "api.reports.email_gate",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.reports.generate",
    routeTemplate: "/api/reports/generate",
    file: "src/app/api/reports/generate/route.ts",
    surface: "reports",
    allowedMethods: ["POST"],
    authRequirement: "session",
    rateLimitBucket: "report-write",
    costPolicy: "report_generation",
    telemetryEvent: "api.reports.generate",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.reports.peer_brief.confirm",
    routeTemplate: "/api/reports/peer-brief/confirm",
    file: "src/app/api/reports/peer-brief/confirm/route.ts",
    surface: "reports",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.reports.peer_brief.confirm",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.research.hamilton",
    routeTemplate: "/api/research/hamilton",
    file: "src/app/api/research/hamilton/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "provider-ai",
    costPolicy: "provider_ai",
    telemetryEvent: "api.research.hamilton",
    failBehavior: "fail_closed",
    auditPriority: "critical",
    notes: "Unauthenticated public AI is disabled.",
  },
  {
    routeId: "api.revalidate",
    routeTemplate: "/api/revalidate",
    file: "src/app/api/revalidate/route.ts",
    surface: "admin",
    allowedMethods: ["POST"],
    authRequirement: "secret",
    rateLimitBucket: "admin-write",
    costPolicy: "none",
    telemetryEvent: "api.revalidate",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.session",
    routeTemplate: "/api/session",
    file: "src/app/api/session/route.ts",
    surface: "auth",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "auth",
    costPolicy: "none",
    telemetryEvent: "api.session",
    failBehavior: "fail_open_audit_only",
    auditPriority: "low",
    notes:
      "Minimal signed-in/initial/isPro/isStaff shape for the site chrome islands; returns signedIn:false on any failure.",
  },
  {
    routeId: "api.v1.fees",
    routeTemplate: "/api/v1/fees",
    file: "src/app/api/v1/fees/route.ts",
    surface: "v1",
    allowedMethods: ["GET", "OPTIONS"],
    authRequirement: "api_key_or_public_read",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.fees",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.v1.index",
    routeTemplate: "/api/v1/index",
    file: "src/app/api/v1/index/route.ts",
    surface: "v1",
    allowedMethods: ["GET", "OPTIONS"],
    authRequirement: "api_key_or_public_read",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.index",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.v1.institutions",
    routeTemplate: "/api/v1/institutions",
    file: "src/app/api/v1/institutions/route.ts",
    surface: "v1",
    allowedMethods: ["GET", "OPTIONS"],
    authRequirement: "api_key_or_public_read",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.institutions",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.v1.revenue",
    routeTemplate: "/api/v1/revenue",
    file: "src/app/api/v1/revenue/route.ts",
    surface: "v1",
    allowedMethods: ["GET", "OPTIONS"],
    authRequirement: "api_key",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.revenue",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes: "Call report service-charge income by quarter, national or by Fed district. Paid keys only.",
  },
  {
    routeId: "api.v1.fee_changes",
    routeTemplate: "/api/v1/fee-changes",
    file: "src/app/api/v1/fee-changes/route.ts",
    surface: "v1",
    allowedMethods: ["GET", "OPTIONS"],
    authRequirement: "api_key",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.fee_changes",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes: "Fee changes detected between reads of an institution's schedule. Paid keys only.",
  },
  {
    routeId: "api.v1.branches",
    routeTemplate: "/api/v1/branches",
    file: "src/app/api/v1/branches/route.ts",
    surface: "v1",
    allowedMethods: ["GET", "OPTIONS"],
    authRequirement: "api_key",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.branches",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes: "Bank branch locations (FDIC Summary of Deposits) for one institution or an area. Paid keys only.",
  },
  {
    routeId: "api.v1.market",
    routeTemplate: "/api/v1/market",
    file: "src/app/api/v1/market/route.ts",
    surface: "v1",
    allowedMethods: ["GET", "OPTIONS"],
    authRequirement: "api_key",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.market",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes: "An institution's local market competitors with deposit share. Paid keys only.",
  },
  {
    routeId: "api.v1.mcp",
    routeTemplate: "/api/v1/mcp",
    file: "src/app/api/v1/mcp/route.ts",
    surface: "v1",
    allowedMethods: ["POST"],
    authRequirement: "api_key",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.mcp",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes: "MCP connector for AI assistants; each tool call runs the matching v1 route with the caller's key. No model call.",
  },
  {
    routeId: "api.v1.openapi",
    routeTemplate: "/api/v1/openapi.json",
    file: "src/app/api/v1/openapi.json/route.ts",
    surface: "v1",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.v1.openapi",
    failBehavior: "fail_open_audit_only",
    auditPriority: "low",
  },
  {
    routeId: "api.webhooks.mailerlite",
    routeTemplate: "/api/webhooks/mailerlite",
    file: "src/app/api/webhooks/mailerlite/route.ts",
    surface: "webhook",
    allowedMethods: ["POST"],
    authRequirement: "secret",
    rateLimitBucket: "webhook",
    costPolicy: "webhook",
    telemetryEvent: "api.webhooks.mailerlite",
    failBehavior: "fail_closed",
    auditPriority: "high",
    notes: "MailerLite unsubscribes, bounces and spam reports written back to leads; HMAC-signed with MAILERLITE_WEBHOOK_SECRET.",
  },
  {
    routeId: "api.webhooks.stripe",
    routeTemplate: "/api/webhooks/stripe",
    file: "src/app/api/webhooks/stripe/route.ts",
    surface: "webhook",
    allowedMethods: ["POST"],
    authRequirement: "stripe_signature",
    rateLimitBucket: "webhook",
    costPolicy: "webhook",
    telemetryEvent: "api.webhooks.stripe",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
] as const satisfies readonly ApiRoutePolicy[];

export type ApiRouteId = (typeof API_ROUTE_POLICIES)[number]["routeId"];

export function getApiRoutePolicy(routeId: string): ApiRoutePolicy {
  const policy = API_ROUTE_POLICIES.find((candidate) => candidate.routeId === routeId);
  if (!policy) {
    throw new Error(`Missing API route policy for ${routeId}`);
  }
  return policy;
}

export function listApiRoutePolicies(): readonly ApiRoutePolicy[] {
  return API_ROUTE_POLICIES;
}
