export type ApiSurface =
  | "admin"
  | "auth"
  | "public"
  | "pro"
  | "reports"
  | "v1"
  | "webhook";

export type ApiAuthRequirement =
  | "public"
  | "session"
  | "admin"
  | "admin_or_analyst"
  | "premium"
  | "api_key_or_public_read"
  | "cron_or_admin"
  | "secret"
  | "stripe_signature";

export type ApiCostPolicy =
  | "none"
  | "provider_ai"
  | "agent_execution"
  | "report_generation"
  | "pdf_generation"
  | "webhook";

export type ApiFailBehavior = "fail_closed" | "fail_open_audit_only";

export interface ApiRoutePolicy {
  routeId: string;
  routeTemplate: string;
  file: string;
  surface: ApiSurface;
  allowedMethods: readonly string[];
  authRequirement: ApiAuthRequirement;
  rateLimitBucket: string;
  costPolicy: ApiCostPolicy;
  telemetryEvent: string;
  failBehavior: ApiFailBehavior;
  auditPriority: "critical" | "high" | "medium" | "low";
  notes?: string;
}

export const ROUTE_POLICY_VERSION = "2026-08-15.api-hardening.v1";

export const API_ROUTE_POLICIES = [
  {
    routeId: "api.admin.agents.runs.execute",
    routeTemplate: "/api/admin/agents/runs/[id]/execute",
    file: "src/app/api/admin/agents/runs/[id]/execute/route.ts",
    surface: "admin",
    allowedMethods: ["POST"],
    authRequirement: "admin",
    rateLimitBucket: "admin-agent-execute",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.agents.runs.execute",
    failBehavior: "fail_closed",
    auditPriority: "critical",
  },
  {
    routeId: "api.admin.agents.tick",
    routeTemplate: "/api/admin/agents/tick",
    file: "src/app/api/admin/agents/tick/route.ts",
    surface: "admin",
    allowedMethods: ["GET", "POST"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.agents.tick",
    failBehavior: "fail_closed",
    auditPriority: "critical",
  },
  {
    routeId: "api.admin.crew",
    routeTemplate: "/api/admin/crew",
    file: "src/app/api/admin/crew/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.crew",
    failBehavior: "fail_closed",
    auditPriority: "low",
    notes: "Crew roster and plain-English activity log; read-only, no provider calls.",
  },
  {
    routeId: "api.admin.documents",
    routeTemplate: "/api/admin/documents/[id]",
    file: "src/app/api/admin/documents/[id]/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "admin",
    rateLimitBucket: "admin-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.documents",
    failBehavior: "fail_closed",
    auditPriority: "low",
    notes: "Redirects to a 1-hour presigned R2 link for a stored source document (the document vault).",
  },
  {
    routeId: "api.admin.crew.daily_brief",
    routeTemplate: "/api/admin/crew/daily-brief",
    file: "src/app/api/admin/crew/daily-brief/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.daily_brief",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Daily Atlas brief email; one visible run per day, no provider calls.",
  },
  {
    routeId: "api.admin.crew.fee_alerts",
    routeTemplate: "/api/admin/crew/fee-alerts",
    file: "src/app/api/admin/crew/fee-alerts/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.crew.fee_alerts",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Daily Atlas fee-change alerts to readers' saved institutions; one visible run per day, no provider calls.",
  },
  {
    routeId: "api.admin.registry.tick",
    routeTemplate: "/api/admin/registry/tick",
    file: "src/app/api/admin/registry/tick/route.ts",
    surface: "admin",
    allowedMethods: ["GET", "POST"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.registry.tick",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Regulatory-registry cron: schedules and runs one deterministic partition step; no provider calls.",
  },
  {
    routeId: "api.admin.registry.run",
    routeTemplate: "/api/admin/registry/run",
    file: "src/app/api/admin/registry/run/route.ts",
    surface: "admin",
    allowedMethods: ["POST"],
    authRequirement: "cron_or_admin",
    rateLimitBucket: "admin-cron",
    costPolicy: "agent_execution",
    telemetryEvent: "api.admin.registry.run",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Queues one regulatory-registry partition as a visible Magellan run; deterministic, no provider calls.",
  },
  {
    routeId: "api.admin.job_health",
    routeTemplate: "/api/admin/job-health",
    file: "src/app/api/admin/job-health/route.ts",
    surface: "admin",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.admin.job_health",
    failBehavior: "fail_open_audit_only",
    auditPriority: "medium",
    notes: "Public health summary; keep deterministic and read-only.",
  },
  {
    routeId: "api.alerts",
    routeTemplate: "/api/alerts",
    file: "src/app/api/alerts/route.ts",
    surface: "public",
    allowedMethods: ["GET", "POST", "DELETE"],
    authRequirement: "session",
    rateLimitBucket: "account-alerts",
    costPolicy: "none",
    telemetryEvent: "api.alerts",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.alerts.unsubscribe",
    routeTemplate: "/api/alerts/unsubscribe",
    file: "src/app/api/alerts/unsubscribe/route.ts",
    surface: "public",
    allowedMethods: ["POST"],
    authRequirement: "secret",
    rateLimitBucket: "account-alerts",
    costPolicy: "none",
    telemetryEvent: "api.alerts.unsubscribe",
    failBehavior: "fail_closed",
    auditPriority: "medium",
    notes: "Signed one-click unsubscribe from fee-change alerts (RFC 8058) and the /email-preferences button.",
  },
  {
    routeId: "api.auth.logout",
    routeTemplate: "/api/auth/logout",
    file: "src/app/api/auth/logout/route.ts",
    surface: "auth",
    allowedMethods: ["POST"],
    authRequirement: "session",
    rateLimitBucket: "auth",
    costPolicy: "none",
    telemetryEvent: "api.auth.logout",
    failBehavior: "fail_closed",
    auditPriority: "low",
  },
  {
    routeId: "api.guides.saved_institutions",
    routeTemplate: "/api/guides/saved-institutions",
    file: "src/app/api/guides/saved-institutions/route.ts",
    surface: "public",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "account-alerts",
    costPolicy: "none",
    telemetryEvent: "api.guides.saved_institutions",
    failBehavior: "fail_open_audit_only",
    auditPriority: "low",
    notes:
      "Personalisation island for static guide pages. Signed-out callers get an empty list, never a 401, so the page never depends on it.",
  },
  {
    routeId: "api.hamilton.chat",
    routeTemplate: "/api/hamilton/chat",
    file: "src/app/api/hamilton/chat/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "admin_or_analyst",
    rateLimitBucket: "provider-ai",
    costPolicy: "provider_ai",
    telemetryEvent: "api.hamilton.chat",
    failBehavior: "fail_closed",
    auditPriority: "critical",
  },
  {
    routeId: "api.hamilton.conversation.messages",
    routeTemplate: "/api/hamilton/conversations/[id]/messages",
    file: "src/app/api/hamilton/conversations/[id]/messages/route.ts",
    surface: "pro",
    allowedMethods: ["GET"],
    authRequirement: "admin_or_analyst",
    rateLimitBucket: "pro-read",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.conversation.messages",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.hamilton.conversations",
    routeTemplate: "/api/hamilton/conversations",
    file: "src/app/api/hamilton/conversations/route.ts",
    surface: "pro",
    allowedMethods: ["GET", "POST"],
    authRequirement: "admin_or_analyst",
    rateLimitBucket: "pro-write",
    costPolicy: "none",
    telemetryEvent: "api.hamilton.conversations",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.hamilton.simulate",
    routeTemplate: "/api/hamilton/simulate",
    file: "src/app/api/hamilton/simulate/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "provider-ai",
    costPolicy: "provider_ai",
    telemetryEvent: "api.hamilton.simulate",
    failBehavior: "fail_closed",
    auditPriority: "critical",
  },
  {
    routeId: "api.health",
    routeTemplate: "/api/health",
    file: "src/app/api/health/route.ts",
    surface: "public",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "health",
    costPolicy: "none",
    telemetryEvent: "api.health",
    failBehavior: "fail_open_audit_only",
    auditPriority: "low",
  },
  {
    routeId: "api.institutions.evidence",
    routeTemplate: "/api/institutions/[id]/evidence",
    file: "src/app/api/institutions/[id]/evidence/route.ts",
    surface: "public",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.institutions.evidence",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.institutions",
    routeTemplate: "/api/institutions",
    file: "src/app/api/institutions/route.ts",
    surface: "public",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.institutions",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.leads",
    routeTemplate: "/api/leads",
    file: "src/app/api/leads/route.ts",
    surface: "public",
    allowedMethods: ["POST"],
    authRequirement: "public",
    rateLimitBucket: "lead-write",
    costPolicy: "none",
    telemetryEvent: "api.leads",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.leads.subscription",
    routeTemplate: "/api/leads/subscription",
    file: "src/app/api/leads/subscription/route.ts",
    surface: "public",
    allowedMethods: ["POST"],
    authRequirement: "public",
    rateLimitBucket: "lead-write",
    costPolicy: "none",
    telemetryEvent: "api.leads.subscription",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.pro.report_pdf",
    routeTemplate: "/api/pro/report-pdf",
    file: "src/app/api/pro/report-pdf/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "pro-export",
    costPolicy: "pdf_generation",
    telemetryEvent: "api.pro.report_pdf",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.reports.download",
    routeTemplate: "/api/reports/[id]/download",
    file: "src/app/api/reports/[id]/download/route.ts",
    surface: "reports",
    allowedMethods: ["GET"],
    authRequirement: "session",
    rateLimitBucket: "report-read",
    costPolicy: "none",
    telemetryEvent: "api.reports.download",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.reports.status",
    routeTemplate: "/api/reports/[id]/status",
    file: "src/app/api/reports/[id]/status/route.ts",
    surface: "reports",
    allowedMethods: ["GET", "PATCH"],
    authRequirement: "session",
    rateLimitBucket: "report-read",
    costPolicy: "none",
    telemetryEvent: "api.reports.status",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.reports.catalog",
    routeTemplate: "/api/reports/catalog",
    file: "src/app/api/reports/catalog/route.ts",
    surface: "reports",
    allowedMethods: ["GET"],
    authRequirement: "session",
    rateLimitBucket: "report-read",
    costPolicy: "none",
    telemetryEvent: "api.reports.catalog",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.reports.email_gate",
    routeTemplate: "/api/reports/email-gate",
    file: "src/app/api/reports/email-gate/route.ts",
    surface: "reports",
    allowedMethods: ["POST"],
    authRequirement: "public",
    rateLimitBucket: "lead-write",
    costPolicy: "none",
    telemetryEvent: "api.reports.email_gate",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.reports.generate",
    routeTemplate: "/api/reports/generate",
    file: "src/app/api/reports/generate/route.ts",
    surface: "reports",
    allowedMethods: ["POST"],
    authRequirement: "session",
    rateLimitBucket: "report-write",
    costPolicy: "report_generation",
    telemetryEvent: "api.reports.generate",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.reports.peer_brief.confirm",
    routeTemplate: "/api/reports/peer-brief/confirm",
    file: "src/app/api/reports/peer-brief/confirm/route.ts",
    surface: "reports",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.reports.peer_brief.confirm",
    failBehavior: "fail_closed",
    auditPriority: "medium",
  },
  {
    routeId: "api.research.hamilton",
    routeTemplate: "/api/research/hamilton",
    file: "src/app/api/research/hamilton/route.ts",
    surface: "pro",
    allowedMethods: ["POST"],
    authRequirement: "premium",
    rateLimitBucket: "provider-ai",
    costPolicy: "provider_ai",
    telemetryEvent: "api.research.hamilton",
    failBehavior: "fail_closed",
    auditPriority: "critical",
    notes: "Unauthenticated public AI is disabled.",
  },
  {
    routeId: "api.revalidate",
    routeTemplate: "/api/revalidate",
    file: "src/app/api/revalidate/route.ts",
    surface: "admin",
    allowedMethods: ["POST"],
    authRequirement: "secret",
    rateLimitBucket: "admin-write",
    costPolicy: "none",
    telemetryEvent: "api.revalidate",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.session",
    routeTemplate: "/api/session",
    file: "src/app/api/session/route.ts",
    surface: "auth",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "auth",
    costPolicy: "none",
    telemetryEvent: "api.session",
    failBehavior: "fail_open_audit_only",
    auditPriority: "low",
    notes:
      "Minimal signed-in/initial/isPro/isStaff shape for the site chrome islands; returns signedIn:false on any failure.",
  },
  {
    routeId: "api.v1.fees",
    routeTemplate: "/api/v1/fees",
    file: "src/app/api/v1/fees/route.ts",
    surface: "v1",
    allowedMethods: ["GET"],
    authRequirement: "api_key_or_public_read",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.fees",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.v1.index",
    routeTemplate: "/api/v1/index",
    file: "src/app/api/v1/index/route.ts",
    surface: "v1",
    allowedMethods: ["GET"],
    authRequirement: "api_key_or_public_read",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.index",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.v1.institutions",
    routeTemplate: "/api/v1/institutions",
    file: "src/app/api/v1/institutions/route.ts",
    surface: "v1",
    allowedMethods: ["GET"],
    authRequirement: "api_key_or_public_read",
    rateLimitBucket: "v1-monthly",
    costPolicy: "none",
    telemetryEvent: "api.v1.institutions",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
  {
    routeId: "api.v1.openapi",
    routeTemplate: "/api/v1/openapi.json",
    file: "src/app/api/v1/openapi.json/route.ts",
    surface: "v1",
    allowedMethods: ["GET"],
    authRequirement: "public",
    rateLimitBucket: "public-read",
    costPolicy: "none",
    telemetryEvent: "api.v1.openapi",
    failBehavior: "fail_open_audit_only",
    auditPriority: "low",
  },
  {
    routeId: "api.webhooks.stripe",
    routeTemplate: "/api/webhooks/stripe",
    file: "src/app/api/webhooks/stripe/route.ts",
    surface: "webhook",
    allowedMethods: ["POST"],
    authRequirement: "stripe_signature",
    rateLimitBucket: "webhook",
    costPolicy: "webhook",
    telemetryEvent: "api.webhooks.stripe",
    failBehavior: "fail_closed",
    auditPriority: "high",
  },
] as const satisfies readonly ApiRoutePolicy[];

export type ApiRouteId = (typeof API_ROUTE_POLICIES)[number]["routeId"];

export function getApiRoutePolicy(routeId: string): ApiRoutePolicy {
  const policy = API_ROUTE_POLICIES.find((candidate) => candidate.routeId === routeId);
  if (!policy) {
    throw new Error(`Missing API route policy for ${routeId}`);
  }
  return policy;
}

export function listApiRoutePolicies(): readonly ApiRoutePolicy[] {
  return API_ROUTE_POLICIES;
}
