/**
 * AnalysisPdfDocument — @react-pdf/renderer document component for Analyze screen exports.
 * Server-side ONLY. Never import this in client components.
 * Called from /api/pro/report-pdf route only (via type: "analysis" dispatch).
 *
 * Design: Mirrors PdfDocument.tsx brand palette — same COLORS, same StyleSheet patterns.
 * No CSS variables (react-pdf cannot resolve them).
 */
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { AnalyzeResponse } from "@/lib/hamilton/types";
import { HAMILTON_ATTRIBUTION } from "@/lib/constants";
import { humanizeAnswerText, shapeHamiltonView, tidyEvidence } from "@/components/hamilton/analyze/parse-response";

// ─── Brand Colors ─────────────────────────────────────────────────────────────
// Exact copy from PdfDocument.tsx — do not use CSS variables here.

const COLORS = {
  textPrimary: "#1c1917",
  textSecondary: "#78716c",
  textTertiary: "#a8a29e",
  accent: "#b45309",
  surface: "#fbf9f4",
  surfaceElevated: "#f5f1e8",
  borderDark: "#d6d0c5",
};

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  page: {
    backgroundColor: COLORS.surface,
    paddingTop: 64,
    paddingBottom: 64,
    paddingLeft: 72,
    paddingRight: 72,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 32,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDark,
    borderBottomStyle: "solid",
  },
  reportTypeBadge: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: COLORS.accent,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 12,
  },
  reportTitle: {
    fontSize: 24,
    fontFamily: "Helvetica-Bold",
    color: COLORS.textPrimary,
    lineHeight: 1.2,
    marginBottom: 8,
  },
  readOnlyNotice: {
    fontSize: 8,
    color: COLORS.textTertiary,
    fontFamily: "Helvetica",
  },
  section: {
    marginBottom: 32,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDark,
    borderBottomStyle: "solid",
  },
  sectionHeading: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: COLORS.textPrimary,
    marginBottom: 12,
    lineHeight: 1.3,
  },
  paragraph: {
    fontSize: 11,
    fontFamily: "Helvetica",
    color: COLORS.textPrimary,
    lineHeight: 1.7,
    marginBottom: 10,
  },
  // The closing section carries no rule or trailing space, which would spill onto a blank page.
  lastSection: {
    marginBottom: 0,
  },
  evidenceRow: {
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.borderDark,
    borderBottomStyle: "solid",
  },
  evidenceLabel: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: COLORS.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 4,
  },
  evidenceValue: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: COLORS.textPrimary,
    lineHeight: 1.4,
  },
  evidenceNote: {
    fontSize: 9,
    fontFamily: "Helvetica",
    color: COLORS.textSecondary,
    lineHeight: 1.5,
    marginTop: 3,
  },
  noteItem: {
    fontSize: 10,
    fontFamily: "Helvetica",
    color: COLORS.textSecondary,
    lineHeight: 1.6,
    marginBottom: 6,
    paddingLeft: 12,
  },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 72,
    right: 72,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderDark,
    borderTopStyle: "solid",
    paddingTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: {
    fontSize: 8,
    fontFamily: "Helvetica",
    color: COLORS.textTertiary,
  },
});

// ─── Component ────────────────────────────────────────────────────────────────

interface AnalysisPdfDocumentProps {
  analysis: AnalyzeResponse;
  analysisFocus: string;
  institutionName?: string;
}

export function AnalysisPdfDocument({
  analysis,
  analysisFocus,
  institutionName,
}: AnalysisPdfDocumentProps) {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // The title is the answer's whole first sentence (older answers saved an 80-character cut);
  // the view below carries the rest, so the lead is not printed twice.
  const view = shapeHamiltonView(humanizeAnswerText(analysis.hamiltonView));
  const title = view.lead || analysis.title;
  const hamiltonViewParagraphs = view.paragraphs;
  const evidence = tidyEvidence(analysis.evidence.metrics);
  // A long implications paragraph reads in short blocks of up to three sentences.
  const meaning = shapeHamiltonView(humanizeAnswerText(analysis.whatThisMeans ?? ""));
  const meaningParagraphs = [[meaning.lead, meaning.paragraphs[0]].filter(Boolean).join(" "), ...meaning.paragraphs.slice(1)].filter(Boolean);

  const readOnlyLine = institutionName
    ? `Generated by ${HAMILTON_ATTRIBUTION} | ${institutionName}`
    : `Generated by ${HAMILTON_ATTRIBUTION}`;

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.reportTypeBadge}>{analysisFocus} Analysis</Text>
          <Text style={styles.reportTitle}>{title}</Text>
          <Text style={styles.readOnlyNotice}>{readOnlyLine}</Text>
        </View>

        {/* Hamilton's View */}
        {hamiltonViewParagraphs.length > 0 ? (
        <View style={styles.section}>
          <Text style={styles.sectionHeading} minPresenceAhead={60}>{"Hamilton's View"}</Text>
          {hamiltonViewParagraphs.map((para, i) => (
            <Text key={i} style={styles.paragraph}>
              {para}
            </Text>
          ))}
        </View>
        ) : null}

        {/* What This Means */}
        {analysis.whatThisMeans ? (
          <View style={styles.section}>
            <Text style={styles.sectionHeading} minPresenceAhead={60}>What This Means</Text>
            {meaningParagraphs.map((para, i) => (
              <Text key={i} style={styles.paragraph}>
                {para}
              </Text>
            ))}
          </View>
        ) : null}

        {/* Why It Matters */}
        {analysis.whyItMatters.length > 0 ? (
          <View style={styles.section} wrap={false}>
            <Text style={styles.sectionHeading}>Why It Matters</Text>
            {analysis.whyItMatters.map((item, i) => (
              <Text key={i} style={styles.noteItem} wrap={false}>
                {"\u2022  "}{humanizeAnswerText(item)}
              </Text>
            ))}
          </View>
        ) : null}

        {/* Evidence: one full-width row per figure, never split across a page */}
        {evidence.length > 0 ? (
          <View style={styles.lastSection}>
            {evidence.map((metric, i) => (
              <View key={i} style={styles.evidenceRow} wrap={false}>
                {/* The heading travels with the first row so it never sits alone at a page foot. */}
                {i === 0 ? <Text style={styles.sectionHeading}>Evidence</Text> : null}
                {metric.label ? <Text style={styles.evidenceLabel}>{metric.label}</Text> : null}
                <Text style={styles.evidenceValue}>{metric.value}</Text>
                {metric.note ? <Text style={styles.evidenceNote}>{metric.note}</Text> : null}
              </View>
            ))}
          </View>
        ) : null}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>{HAMILTON_ATTRIBUTION}</Text>
          <Text style={styles.footerText}>{today}</Text>
        </View>
      </Page>
    </Document>
  );
}
